INFO     127.0.0.1 [18/May/2020:18:12:38 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
INFO     127.0.0.1 [18/May/2020:18:17:39 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=1,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
INFO     127.0.0.1 [18/May/2020:18:17:54 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:17:58 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=15,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
INFO     127.0.0.1 [18/May/2020:18:18:21 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:18:25 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     Archive downloaded success
INFO     127.0.0.1 [18/May/2020:18:18:26 +0000] "GET /archive/7kna/ HTTP/1.1" 200 10989648 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:18:29 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
INFO     127.0.0.1 [18/May/2020:18:18:49 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
WARNING  Download was interrupted
INFO     127.0.0.1 [18/May/2020:18:18:50 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:19:10 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=15
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
WARNING  Download was interrupted
INFO     127.0.0.1 [18/May/2020:18:29:52 +0000] "GET /archive/rur2/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:30:06 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
WARNING  Download was interrupted
INFO     127.0.0.1 [18/May/2020:18:30:06 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:30:23 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:31:09 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=15
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
INFO     127.0.0.1 [18/May/2020:18:43:30 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 33, in archivate
    timeout=15
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
INFO     127.0.0.1 [18/May/2020:18:43:44 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
WARNING  Download was interrupted
INFO     127.0.0.1 [18/May/2020:18:43:45 +0000] "GET /archive/7kna/ HTTP/1.1" 200 351 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:47:27 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:48:05 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
WARNING  Download was interrupted
INFO     127.0.0.1 [18/May/2020:18:48:06 +0000] "GET /archive/7kna/ HTTP/1.1" 200 351 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
WARNING  Download was interrupted
INFO     127.0.0.1 [18/May/2020:18:48:39 +0000] "GET /archive/7kna/ HTTP/1.1" 200 351 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
WARNING  Download was interrupted
INFO     127.0.0.1 [18/May/2020:18:49:54 +0000] "GET /archive/7kna/ HTTP/1.1" 200 351 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:50:12 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:18:50:13 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:20:46:04 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:20:46:21 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:20:47:28 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:20:47:32 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:20:47:44 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:20:49:24 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:20:54:00 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 36, in archivate
    proc = asyncio.subprocess.Popen()
AttributeError: module 'asyncio.subprocess' has no attribute 'Popen'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
INFO     127.0.0.1 [18/May/2020:20:54:19 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "server.py", line 36, in archivate
    proc = asyncio.subprocess.Popen()
AttributeError: module 'asyncio.subprocess' has no attribute 'Popen'
ERROR    Unhandled exception
Traceback (most recent call last):
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/Users/oleh_kost/PycharmProjects/async_microservice/venv/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
INFO     127.0.0.1 [18/May/2020:20:54:34 +0000] "GET / HTTP/1.1" 200 3977 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
WARNING  Download was interrupted
INFO     127.0.0.1 [18/May/2020:20:54:36 +0000] "GET /archive/7kna/ HTTP/1.1" 200 351 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
INFO     127.0.0.1 [18/May/2020:20:57:24 +0000] "GET /archive/7kna/ HTTP/1.1" 200 214 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
